import React from "react";
import { View, Text, TouchableOpacity, TextInput } from "react-native";
export function Card({children,style,theme,glow}){ return <View style={[{backgroundColor:theme.surface,borderWidth:1,borderColor:glow?theme.accent:theme.border,borderRadius:16,padding:16,marginBottom:12,shadowColor:glow?theme.accent:"#000",shadowOpacity:glow?0.35:0.1,shadowRadius:glow?12:4,shadowOffset:{width:0,height:2},elevation:glow?8:3},style]}>{children}</View>; }
export function SectionTitle({children,theme}){ return <Text style={{fontSize:11,fontWeight:"700",color:theme.textMuted,textTransform:"uppercase",letterSpacing:1.5,marginBottom:12}}>{children}</Text>; }
export function StatCard({value,label,color,theme}){ return <View style={{flex:1,backgroundColor:theme.surface2,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:12,alignItems:"center"}}><Text style={{fontSize:16,fontWeight:"800",color:color||theme.green}}>{value}</Text><Text style={{fontSize:9,color:theme.textMuted,marginTop:3,textTransform:"uppercase",letterSpacing:1,textAlign:"center"}}>{label}</Text></View>; }
export function MonthNav({month,year,onPrev,onNext,theme,MONTHS_SHORT}){ return <View style={{flexDirection:"row",alignItems:"center",marginBottom:14,gap:8}}><TouchableOpacity onPress={onPrev} style={{backgroundColor:theme.surface2,borderWidth:1,borderColor:theme.border,borderRadius:10,paddingHorizontal:14,paddingVertical:7}}><Text style={{color:theme.text,fontWeight:"700",fontSize:16}}>‹</Text></TouchableOpacity><Text style={{flex:1,textAlign:"center",fontWeight:"700",fontSize:15,color:theme.text}}>{MONTHS_SHORT[month]} {year}</Text><TouchableOpacity onPress={onNext} style={{backgroundColor:theme.surface2,borderWidth:1,borderColor:theme.border,borderRadius:10,paddingHorizontal:14,paddingVertical:7}}><Text style={{color:theme.text,fontWeight:"700",fontSize:16}}>›</Text></TouchableOpacity></View>; }
export function CatBar({category,spent,total,theme}){ const pct=total>0?Math.min((spent/total)*100,100):0; return <View style={{height:6,backgroundColor:theme.border,borderRadius:99,overflow:"hidden",flex:1}}><View style={{height:"100%",width:`${pct}%`,backgroundColor:category.color,borderRadius:99}}/></View>; }
export function Pill({label,color,theme}){ return <View style={{backgroundColor:color+"22",paddingHorizontal:10,paddingVertical:3,borderRadius:99,borderWidth:1,borderColor:color+"44"}}><Text style={{fontSize:11,color,fontWeight:"600"}}>{label}</Text></View>; }
export function PrimaryButton({label,onPress,theme}){ return <TouchableOpacity onPress={onPress} style={{backgroundColor:theme.accent,borderRadius:14,padding:15,alignItems:"center",shadowColor:theme.accent,shadowOpacity:0.4,shadowRadius:10,elevation:6}} activeOpacity={0.85}><Text style={{color:"#fff",fontWeight:"700",fontSize:16}}>{label}</Text></TouchableOpacity>; }
export function StyledInput({theme,style,...props}){ return <TextInput style={[{backgroundColor:theme.surface2,borderWidth:1,borderColor:theme.border,borderRadius:12,padding:13,color:theme.text,fontSize:15},style]} placeholderTextColor={theme.textMuted} {...props}/>; }
export function Toast({message,type}){ if(!message)return null; const bg=type==="error"?"#FF4444":"#00FF94"; const color=type==="error"?"#fff":"#000"; return <View style={{position:"absolute",top:60,alignSelf:"center",backgroundColor:bg,paddingHorizontal:20,paddingVertical:10,borderRadius:99,zIndex:999,elevation:10}}><Text style={{color,fontWeight:"700",fontSize:13}}>{message}</Text></View>; }
